# Generated by Django 4.2.11 on 2026-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_banner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
